### ISSUE TITLE
Incomplete builder

### ISSUE THREAD

**Issue by edugof** [affishaikh/kotlin-builder-generator#4]
For the data class:

```
data class QueryParameter(val searchField: String,
                              val searchValue: String,
                              val paginationFirst: Int,
                              val paginationAfter: Long?)
```

The following builder class is created:

```data class QueryParameterBuilder(
val searchField: String = "",
val searchValue: String = "",
val paginationFirst: Int = 0,
val paginationAfter: Long? = null
) {
fun build(): QueryParameter {
return QueryParameter(
searchField = searchField,
searchValue = searchValue,
paginationFirst = paginationFirst,
paginationAfter = paginationAfter
)
}
}
```

It doesn't contain any function besides the `build()`, so it's not really a builder.

**Comment by affishaikh** [comment]
Hi @edugof , there is no need for any other function besides `build()`. Because we are using the kotlin default parameters. With this you can create different representation using the same constructor of the Builder class.

Consider your above example, if you want to create an object of `QueryParamter` with only searchField and searchValue you can do so by

`
QueryParameterBuilder(searchField = "name", searchValue = "L").build()
`
